import {
  checkMaterializedArtifact,
  checkManifestDigest,
  manifestDigest,
  manifestSafetyIssues,
  type MaterializedArtifacts,
  type MaterializationIssue,
} from "./materialize-common.js";
import { materializeDocs } from "./materialize-docs.js";
import { materializeRuntime } from "./materialize-runtime.js";
import type { SemanticManifest } from "./manifest-model.js";

export type MaterializedArtifactCandidate = {
  readonly runtime?: string;
  readonly documentation?: string;
  readonly manifestDigest?: string;
};

/** Materialize every committed downstream artifact from one manifest value. */
export const materializeArtifacts = (manifest: SemanticManifest): MaterializedArtifacts => ({
  runtime: materializeRuntime(manifest),
  documentation: materializeDocs(manifest),
  manifestDigest: manifestDigest(manifest),
});

/**
 * Compare committed/generated bytes without writing. Every issue is explicit so
 * CI can distinguish omission, stale provenance, metadata drift, and hand edits.
 */
export const checkMaterializedArtifacts = (
  manifest: SemanticManifest,
  candidate: MaterializedArtifactCandidate,
): readonly MaterializationIssue[] => {
  const safetyIssues = manifestSafetyIssues(manifest);
  if (safetyIssues.length > 0) return safetyIssues;

  const expected = materializeArtifacts(manifest);
  return [
    ...checkManifestDigest(manifest, candidate.manifestDigest),
    ...checkMaterializedArtifact(manifest, "runtime", candidate.runtime, expected.runtime),
    ...checkMaterializedArtifact(
      manifest,
      "documentation",
      candidate.documentation,
      expected.documentation,
    ),
  ];
};

export {
  checkManifestBytes,
  manifestDigest,
  manifestSafetyIssues,
} from "./materialize-common.js";
export type {
  MaterializedArtifact,
  MaterializedArtifacts,
  MaterializationIssue,
  MaterializationIssueCode,
} from "./materialize-common.js";
